# Generated by Django 3.1.1 on 2020-09-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailssent',
            name='date_sent',
            field=models.DateField(auto_now=True),
        ),
    ]
